version: 0.2

env:
  variables:
    DATABASE_URI: "sqlite:///:memory:"
    JWT_SECRET_KEY: "clave-secreta"
    PYTHONPATH: "."

phases:
  install:
    commands:
      - echo "Instalando dependencias..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Mostrando directorio actual:"
      - pwd
      - echo "Contenido (ls -R):"
      - ls -R
      - echo "Ejecutando pruebas unitarias (antes, python -m pytest tests):"
      - python -m pytest tests --maxfail=1 --disable-warnings -v
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 463470985984.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Empaquetando la aplicación..."
      - docker build -t blacklists .
      - docker tag blacklists:latest 463470985984.dkr.ecr.us-east-1.amazonaws.com/blacklists:latest

  post_build:
    commands:
      - echo "Pushing docker..."
      - docker push 463470985984.dkr.ecr.us-east-1.amazonaws.com/blacklists:latest
      - printf '{"ImageURI":"%s"}' 463470985984.dkr.ecr.us-east-1.amazonaws.com/blacklists:latest > imageDetail.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
