version: 0.2

env:
  variables:
    DATABASE_URI: "sqlite:///:memory:"
    JWT_SECRET_KEY: "clave-secreta"
    PYTHONPATH: "."

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - python -m pytest tests --maxfail=1 --disable-warnings -v

  build:
    commands:
      - zip -r artifact.zip \
          application.py \
          src/ \
          requirements.txt \
          Procfile \
          .flaskenv

artifacts:
  files:
    - artifact.zip
