version: 0.2

env:
  variables:
    DATABASE_URI: "sqlite:///:memory:"
    JWT_SECRET_KEY: "clave-secreta"
    PYTHONPATH: "."

phases:
  install:
    commands:
      - echo "Instalando dependencias..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Version..."
      - python --version
      - echo "Versiones libs"
      - pip list
      - python -m pytest tests
      - echo "Ejecutando pruebas unitarias..."
      - pytest --maxfail=1 --disable-warnings -v

  build:
    commands:
      - echo "Empaquetando la aplicación..."
      - zip -r artifact.zip application.py src/ tests/ requirements.txt .flaskenv

artifacts:
  files:
    - artifact.zip
